### ISSUE TITLE
Call to a member function update() on null

### ISSUE THREAD

**Issue by michelleprather** [bicknoyle/multistep-tutorial#2]
I am receiving the following error "FatalThrowableError in AccountsController.php line 207:
Call to a member function update() on null" after my first form is submitted. I had it working and all of a sudden it stopped and  I am unable to identify the problem. My code can be found via the link below. Please advise. http://stackoverflow.com/questions/40352861/laravel-multistep-form-call-to-a-member-function-update-on-null
![screen shot 2016-10-31 at 3 00 33 pm](https://cloud.githubusercontent.com/assets/13989824/19896310/19d84188-a011-11e6-8e37-e0ad9036127d.png)
![screen shot 2016-10-31 at 3 01 06 pm](https://cloud.githubusercontent.com/assets/13989824/19896311/19d9bdce-a011-11e6-86ac-a2a826a83750.png)
![screen shot 2016-10-31 at 3 01 34 pm](https://cloud.githubusercontent.com/assets/13989824/19896313/19da56da-a011-11e6-9c41-1e54a5344fa0.png)
![screen shot 2016-10-31 at 3 02 24 pm](https://cloud.githubusercontent.com/assets/13989824/19896312/19da3470-a011-11e6-9ab6-455201770535.png)
![screen shot 2016-10-31 at 3 57 43 pm](https://cloud.githubusercontent.com/assets/13989824/19896314/19df1896-a011-11e6-8105-71c2f2b95380.png)

**Comment by bicknoyle** [comment]
This seems to be a discussion geared towards your own implementation of the code and the tutorial, rather than an with the code here. So, I replied to your comment on the blog because I felt the discussion made more sense there: http://bicknoyle.com/blog/2015/09/29/building-a-multi-step-survey-with-laravel-5-1-part-1/#disqus_thread
